### ISSUE TITLE
Leaflet nominatim URL changed

### ISSUE THREAD

**Issue by LauraStatik** [statikbe/craft#136] opened 2023-09-12 09:43 UTC
In the leaflet component use this URL to get the coordinates. 

```
if (map.getAttribute('data-address')) {
      Ajax.call({
        url: `https://nominatim.openstreetmap.org/search?q=${map.getAttribute(
          'data-address'
        )}&format=json&addressdetails=1&limit=1`,
        success: (data) => {
          leaflet.marker([data[0].lat, data[0].lon]).addTo(lmap);
          lmap.setView([data[0].lat, data[0].lon], 14);
        },
      });
    }
```

**Comment by HannahDeWachter** [comment] 2023-09-12 09:47
Duplicate of #126

**Closed** 2023-09-12 18:49 UTC
